### PR TITLE
Fix: issue #76

### PR DESCRIPTION
**Pull request by Antoninich**
It is more correct to change the description line in signum-node.
image

### CODE REVIEW

**Comment by pir8radio** [comment]
I would rather not do one off things,  i hope that the devs change this description to match SRC44 so we can just decode it like we do everything else in the explorer.  

Example this:
image

Becomes this:
image

**Comment by ohager** [comment]
As I said already

> I would rather not do one off things, i hope that the devs change this description to match SRC44 so we can just decode it like we do everything else in the explorer.
> 
> Example this: image
> 
> Becomes this: image

I mentioned it [https://github.com/signum-network/signum-explorer/issues/76#issuecomment-1804101347](here)... The NFT was created before SRC44... the contracts descriptor is not SRC44 compatible, but if you resolve the IPFS hash in the `descriptor` you get a JSON with all media data. Changing the descriptor for NFT contracts now, is much more effort than treating it in the explorer tbh. We have an entire backend and some additional tools that uses the non-SRC44 format

Here is an example of the JSON in referenced in NFT `descriptor` field.
https://ipfs.io/ipfs/bafkreifgan3pg344vhz3tnjq26mzfmt4cmxy5lb6y74jkxobrz4xzq54lm

from this NFT https://chain.signum.network/at/2978638295822152791

**Comment by ohager** [comment]
We are changing the NFTs description to be SRC44 compatible... I think we can close this PR.

**Comment by pir8radio** [comment]
closing, thanks @ohager

**Pull request closed without merging**
