### PR TITLE
Remove active port for the chain from the announcedAddress

### PR DESCRIPTION
**Pull request by frankTheTank72**

### CODE REVIEW

**Review by jjos2372 — CHANGES_REQUESTED** [review]
Please use something like:
```python
        default_port = ":" + str(settings.DEFAULT_P2P_PORT)
        peer_info["announcedAddress"] = peer_info["announcedAddress"].replace(default_port,"")
```

**Comment by pir8radio** [comment]
may want to use django logic..    if testnet..    what if production user wants to use port 7123 for production node.. it is allowed..    maybe just hide all ports if on testnet?

**Comment by jjos2372** [comment]
> may want to use django logic.. if testnet.. what if production user wants to use port 7123 for production node.. it is allowed.. maybe just hide all ports if on testnet?

`settings.DEFAULT_P2P_PORT` already comes from the `.env` file and is correct for testnet/mainnet.

**Comment by frankTheTank72** [comment]
done @jjos2372

**Pull request merged**
